[package]
name = "websocket-example"
version = "0.1.0"
authors = ["Oussama <md.oussama@gmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
websocket = { path = "../" }
application = {path = "../../application" }